default_context:
  project_name: 'Hello FastAPI'
  project_slug: 'hello-fastapi'
  domain_main: 'hello-fastapi.com'
  domain_staging: 'stage.hello-fastapi.com'
  docker_swarm_stack_name_main: 'hello-fastapi-com'
  docker_swarm_stack_name_staging: 'stage-hello-fastapi-com'
  secret_key: 'bf58b6cbca3831f941f143b342199a261e7382798d785e3001665b52d037b57d'
  first_superuser: 'admin@hello-fastapi.com'
  first_superuser_password: 'admin1234'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.hello-fastapi.com, https://stage.hello-fastapi.com, https://hello-fastapi.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@hello-fastapi.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'admin@hello-fastapi.com'
  pgadmin_default_user_password: 'admin1234'
  traefik_constraint_tag: 'hello-fastapi.com'
  traefik_constraint_tag_staging: 'stage.hello-fastapi.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin1234'
  sentry_dsn: ''
  docker_image_prefix: 'hello-fastapi'
  docker_image_backend: 'hello-fastapi-backend'
  docker_image_celeryworker: 'hello-fastapi-celeryworker'
  docker_image_frontend: 'hello-fastapi-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
